### ISSUE TITLE
This would be very useful in Home Assistant/ Hass.io

### ISSUE THREAD

**Issue by Cloolalang** [gambitcomminc/mqtt-stats#3]
Good project, Im currently trying toi work out how much traffic I have on my Mysensors Radio channel., this would make it very easy to see as all the RF traffic flows via the MQTT gateway topics.
I am using Hass.io, I have no idea if this could be made into an Addon, but it would be a wonderful tool if it could.
Cheers
Patrick

**Comment by gambitcomminc** [comment]
We wrote the utility, it's open source, you can put it whereever you want. Go for it.
